sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - maven_central
      - udf_coverage
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "8.23.1"
    - "7.1.25"
