sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - maven_central
      - lombok
      - udf_coverage
linkReplacements:
  - https://awhitford.github.com/lombok.maven/lombok-maven-plugin/|http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/
  - http://www.gnu.org/licenses/lgpl.txt|https://www.gnu.org/licenses/lgpl-3.0.txt
