package com.exasol.adapter.document.edml;

import lombok.*;
import lombok.experimental.SuperBuilder;

/**
 * Abstract base for EDML mappings that map to an Exasol {@code VARCHAR} column.
 */
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@SuperBuilder
@Data
@SuppressWarnings("java:S1170") // sonar can't deal with Lombok
public abstract class AbstractToVarcharColumnMapping extends AbstractToColumnMapping {
    @Builder.Default
    private final int varcharColumnSize = 254;

    /**
     * Builder class. The content of the builder is generated by lombok. We need this class declared here since the
     * Javadoc generation fails otherwise.
     *
     * @param <C> type used by lombok
     * @param <B> type used by lombok
     */
    public abstract static class AbstractToVarcharColumnMappingBuilder<C extends AbstractToVarcharColumnMapping, B extends AbstractToVarcharColumnMapping.AbstractToVarcharColumnMappingBuilder<C, B>>
            extends AbstractToColumnMapping.AbstractToColumnMappingBuilder<C, B> {

    }
}
