package com.exasol.adapter.document.edml;

import lombok.Builder;
import lombok.Data;
import lombok.experimental.SuperBuilder;

/**
 * Abstract base for EDML mappings that map to an Exasol column.
 */
@SuperBuilder
@Data
@SuppressWarnings("java:S1170") // sonar can't deal with Lombok
public abstract class AbstractToColumnMapping implements MappingDefinition {
    private final String destinationName;
    private final String description;
    @Builder.Default
    private final KeyType key = KeyType.NONE;
    @Builder.Default
    private final boolean required = false;

    /**
     * Builder class. The content of the builder is generated by lombok. We need this class declared here since the
     * Javadoc generation fails otherwise.
     *
     * @param <C> type used by lombok
     * @param <B> type used by lombok
     */
    @SuppressWarnings("java:S1610") // class generated by lombok
    public abstract static class AbstractToColumnMappingBuilder<C extends AbstractToColumnMapping, B extends AbstractToColumnMapping.AbstractToColumnMappingBuilder<C, B>> {

    }
}
